
version: '3.7'

services:
    appimage:
        cap_drop:
            - SYS_ADMIN
        container_name: ${CID}
        working_dir: /root
        privileged: true
        build:
            context: app/docker
        volumes:
            - ./app:/root:cached
